# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/eduardo/Desktop/RecoleccionNotas_CronicaReg/CronicaRegNotesRetriver/QTdesiner/GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import json
### own created classes
from Google_API_Credential import Loging_Google_API
from GmailAPI import Mailing

class Ui_CronicaRegNotesRetriver(object):
    def setupUi(self, CronicaRegNotesRetriver):
        CronicaRegNotesRetriver.setObjectName("CronicaRegNotesRetriver")
        CronicaRegNotesRetriver.resize(605, 399)
        self.centralwidget = QtWidgets.QWidget(CronicaRegNotesRetriver)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 591, 351))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setIconSize(QtCore.QSize(40, 40))
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.TabMailConf = QtWidgets.QWidget()
        self.TabMailConf.setObjectName("TabMailConf")
        self.label = QtWidgets.QLabel(self.TabMailConf)
        self.label.setGeometry(QtCore.QRect(20, 20, 171, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.TabMailConf)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 171, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.TabMailConf)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 171, 21))
        self.label_3.setObjectName("label_3")
        self.APIConf_PB_Apply = QtWidgets.QPushButton(self.TabMailConf)
        self.APIConf_PB_Apply.setGeometry(QtCore.QRect(450, 290, 131, 32))
        self.APIConf_PB_Apply.setObjectName("APIConf_PB_Apply")
        self.APIConf_LEdit_CredPath = QtWidgets.QLineEdit(self.TabMailConf)
        self.APIConf_LEdit_CredPath.setGeometry(QtCore.QRect(20, 40, 311, 21))
        self.APIConf_LEdit_CredPath.setObjectName("APIConf_LEdit_CredPath")
        self.APIConf_LEdit_AddFrom = QtWidgets.QLineEdit(self.TabMailConf)
        self.APIConf_LEdit_AddFrom.setGeometry(QtCore.QRect(20, 90, 311, 21))
        self.APIConf_LEdit_AddFrom.setObjectName("APIConf_LEdit_AddFrom")
        self.APIConf_LEdit_AddTo = QtWidgets.QLineEdit(self.TabMailConf)
        self.APIConf_LEdit_AddTo.setGeometry(QtCore.QRect(20, 143, 311, 21))
        self.APIConf_LEdit_AddTo.setObjectName("APIConf_LEdit_AddTo")
        self.APIConf_PB_Log = QtWidgets.QPushButton(self.TabMailConf)
        self.APIConf_PB_Log.setGeometry(QtCore.QRect(360, 50, 231, 51))
        self.APIConf_PB_Log.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.APIConf_PB_Log.setAutoRepeatDelay(300)
        self.APIConf_PB_Log.setObjectName("APIConf_PB_Log")
        self.label_5 = QtWidgets.QLabel(self.TabMailConf)
        self.label_5.setGeometry(QtCore.QRect(368, 56, 40, 38))
        self.label_5.setText("")
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setPixmap(QtGui.QPixmap("/Users/eduardo/Desktop/RecoleccionNotas_CronicaReg/CronicaRegNotesRetriver/QTdesiner/GoogleBTNLOGO.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.APIConf_LB_State = QtWidgets.QLabel(self.TabMailConf)
        self.APIConf_LB_State.setGeometry(QtCore.QRect(449, 100, 131, 20))
        self.APIConf_LB_State.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.APIConf_LB_State.setObjectName("APIConf_LB_State")
        self.tabWidget.addTab(self.TabMailConf, "")
        self.TabSendNotes = QtWidgets.QWidget()
        self.TabSendNotes.setObjectName("TabSendNotes")
        self.SenNo_PB_Verify = QtWidgets.QPushButton(self.TabSendNotes)
        self.SenNo_PB_Verify.setGeometry(QtCore.QRect(240, 170, 113, 32))
        self.SenNo_PB_Verify.setObjectName("SenNo_PB_Verify")
        self.SenNo_PB_Send = QtWidgets.QPushButton(self.TabSendNotes)
        self.SenNo_PB_Send.setGeometry(QtCore.QRect(420, 170, 113, 32))
        self.SenNo_PB_Send.setObjectName("SenNo_PB_Send")
        self.SenNo_PB_Clear = QtWidgets.QPushButton(self.TabSendNotes)
        self.SenNo_PB_Clear.setGeometry(QtCore.QRect(70, 170, 113, 32))
        self.SenNo_PB_Clear.setObjectName("SenNo_PB_Clear")
        self.SenNo_LEdit_Link = QtWidgets.QLineEdit(self.TabSendNotes)
        self.SenNo_LEdit_Link.setGeometry(QtCore.QRect(10, 40, 551, 21))
        self.SenNo_LEdit_Link.setObjectName("SenNo_LEdit_Link")
        self.label_4 = QtWidgets.QLabel(self.TabSendNotes)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 191, 16))
        self.label_4.setObjectName("label_4")
        self.SenNo_progressBar = QtWidgets.QProgressBar(self.TabSendNotes)
        self.SenNo_progressBar.setGeometry(QtCore.QRect(110, 270, 341, 31))
        self.SenNo_progressBar.setProperty("value", 24)
        self.SenNo_progressBar.setObjectName("SenNo_progressBar")
        self.SenNo_LB_State = QtWidgets.QLabel(self.TabSendNotes)
        self.SenNo_LB_State.setGeometry(QtCore.QRect(110, 260, 271, 16))
        self.SenNo_LB_State.setObjectName("SenNo_LB_State")
        self.SenNo_TEdit_VerTitle = QtWidgets.QTextEdit(self.TabSendNotes)
        self.SenNo_TEdit_VerTitle.setGeometry(QtCore.QRect(10, 90, 551, 71))
        self.SenNo_TEdit_VerTitle.setObjectName("SenNo_TEdit_VerTitle")
        self.label_7 = QtWidgets.QLabel(self.TabSendNotes)
        self.label_7.setGeometry(QtCore.QRect(10, 70, 191, 16))
        self.label_7.setObjectName("label_7")
        self.tabWidget.addTab(self.TabSendNotes, "")
        self.TabAppComments = QtWidgets.QWidget()
        self.TabAppComments.setObjectName("TabAppComments")
        self.AppCom_TEdit_body = QtWidgets.QTextEdit(self.TabAppComments)
        self.AppCom_TEdit_body.setGeometry(QtCore.QRect(20, 80, 541, 201))
        self.AppCom_TEdit_body.setObjectName("AppCom_TEdit_body")
        self.AppCom_LEdit_Title = QtWidgets.QLineEdit(self.TabAppComments)
        self.AppCom_LEdit_Title.setGeometry(QtCore.QRect(20, 40, 541, 21))
        self.AppCom_LEdit_Title.setText("")
        self.AppCom_LEdit_Title.setObjectName("AppCom_LEdit_Title")
        self.AppCom_PB_Submit = QtWidgets.QPushButton(self.TabAppComments)
        self.AppCom_PB_Submit.setGeometry(QtCore.QRect(450, 290, 113, 32))
        self.AppCom_PB_Submit.setObjectName("AppCom_PB_Submit")
        self.label_6 = QtWidgets.QLabel(self.TabAppComments)
        self.label_6.setGeometry(QtCore.QRect(20, 20, 221, 16))
        self.label_6.setObjectName("label_6")
        self.AppCom_PB_Clear = QtWidgets.QPushButton(self.TabAppComments)
        self.AppCom_PB_Clear.setGeometry(QtCore.QRect(330, 290, 113, 32))
        self.AppCom_PB_Clear.setObjectName("AppCom_PB_Clear")
        self.SenNo_LB_State_2 = QtWidgets.QLabel(self.TabAppComments)
        self.SenNo_LB_State_2.setGeometry(QtCore.QRect(20, 290, 271, 16))
        self.SenNo_LB_State_2.setObjectName("SenNo_LB_State_2")
        self.tabWidget.addTab(self.TabAppComments, "")
        CronicaRegNotesRetriver.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(CronicaRegNotesRetriver)
        self.statusbar.setObjectName("statusbar")
        CronicaRegNotesRetriver.setStatusBar(self.statusbar)

        self.retranslateUi(CronicaRegNotesRetriver)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CronicaRegNotesRetriver)

    def retranslateUi(self, CronicaRegNotesRetriver):
        _translate = QtCore.QCoreApplication.translate
        CronicaRegNotesRetriver.setWindowTitle(_translate("CronicaRegNotesRetriver", "CronicaRegNotesRetriver"))
        self.label.setText(_translate("CronicaRegNotesRetriver", "Credentials Path"))
        self.label_2.setText(_translate("CronicaRegNotesRetriver", "Address mail from"))
        self.label_3.setText(_translate("CronicaRegNotesRetriver", "Address mail to"))
        self.APIConf_PB_Apply.setText(_translate("CronicaRegNotesRetriver", "Apply changes"))
        self.APIConf_PB_Log.setText(_translate("CronicaRegNotesRetriver", "Log-In With google"))
        self.APIConf_LB_State.setText(_translate("CronicaRegNotesRetriver", "Need to Log-In"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabMailConf), _translate("CronicaRegNotesRetriver", "API/Gmail config"))
        self.SenNo_PB_Verify.setText(_translate("CronicaRegNotesRetriver", "Verify"))
        self.SenNo_PB_Send.setText(_translate("CronicaRegNotesRetriver", "Send"))
        self.SenNo_PB_Clear.setText(_translate("CronicaRegNotesRetriver", "Clear"))
        self.label_4.setText(_translate("CronicaRegNotesRetriver", "Link to get its note"))
        self.SenNo_LB_State.setText(_translate("CronicaRegNotesRetriver", "Ready to get notes"))
        self.label_7.setText(_translate("CronicaRegNotesRetriver", "Verify note title to be send"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabSendNotes), _translate("CronicaRegNotesRetriver", "Sending notes"))
        self.AppCom_TEdit_body.setHtml(_translate("CronicaRegNotesRetriver", "Send a comment to developper"))
        self.AppCom_PB_Submit.setText(_translate("CronicaRegNotesRetriver", "Submit"))
        self.label_6.setText(_translate("CronicaRegNotesRetriver", "Improvement name"))
        self.AppCom_PB_Clear.setText(_translate("CronicaRegNotesRetriver", "Clear"))
        self.SenNo_LB_State_2.setText(_translate("CronicaRegNotesRetriver", "Ready to send comment"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabAppComments), _translate("CronicaRegNotesRetriver", "App comments"))
    
    ####  App Instances 
    ## Instances init
        with open("/content/appConfig.json", "r") as read_file:
            data = json.load(read_file)
        self.GoogleClientAPI = Loging_Google_API()
        self.GmailMailling = Mailing(data["MailFrom"])
        
    #####  Buttons action #####
    
        ### Tab API Conf  
        self.APIConf_PB_Log.clicked.connect(self.API_Log)

    def API_Log(self):
        print("clicked") # we will just print clicked when the button is pressed
        
    def ApplyConfig(self):
        with open("/Users/eduardo/Desktop/RecoleccionNotas_CronicaReg/CronicaRegNotesRetriver/json/appConfig.json", "r") as read_file:
            data = json.load(read_file)
        
        ### TabSendNotes
        
        ### TabAppComments
    
    ##### TextInput getting ####
        ### Tab API Conf 
        
        ### TabSendNotes
        
        ### TabAppComments
        
    
    ##### lables modifs
        ### Tab API Conf 
        
        ### TabSendNotes 
        
        ### TabAppComments


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CronicaRegNotesRetriver = QtWidgets.QMainWindow()
    ui = Ui_CronicaRegNotesRetriver()
    ui.setupUi(CronicaRegNotesRetriver)
    CronicaRegNotesRetriver.show()
    sys.exit(app.exec_())
